In [2]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
i[0:4]

array([10, 20, 30, 40])

In [6]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
i[2:4]

array([30, 40])

In [8]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
i[4:]

array([50, 60])

In [10]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
i[ : 4]

array([10, 20, 30, 40])

In [12]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
i[-2:-1]

array([50])

In [14]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
i[1:-2]

array([20, 30, 40])

In [16]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
i[0:4:3]

array([10, 40])

In [18]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
i[ : : 4] 

array([10, 50])

In [25]:
import numpy as np
i = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
i[0, 0:2]

array([1, 2])

In [27]:
import numpy as np
i = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
i[1, 1:2]

array([7])

In [34]:
import numpy as np
i = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
i[2, 1:2]

array([12])

In [36]:
import numpy as np
i = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
i[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])